In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df=pd.read_csv('dress_dataset_1000.csv')
df_1=pd.read_csv('dress_dataset_1000.csv')

In [3]:
df.head()

Weather Color Palette    Pattern Feeling Clothing Fit   Dress Name  \
0   Windy       Neutral    Stripes  Trendy        Tight      Bodycon   
1   Snowy         Earth  Geometric  Unique    Oversized  Long Sleeve   
2   Sunny        Bright     Floral  Casual        Loose        Tunic   
3   Windy       Neutral    Stripes  Trendy        Tight       Peplum   
4   Windy       Neutral    Stripes  Trendy        Tight        Shirt   

                                         Description  
0  A form-fitting dress that hugs the body, often...  
1  A dress with long sleeves, often featuring pas...  
2  A comfortable, long top that can be worn as a ...  
3  A dress with a flared ruffle attached at the w...  
4  A relaxed, button-down dress with a loose fit,...

In [4]:
df = df.drop(columns=['Description'])

In [5]:
df.head()

Weather Color Palette    Pattern Feeling Clothing Fit   Dress Name
0   Windy       Neutral    Stripes  Trendy        Tight      Bodycon
1   Snowy         Earth  Geometric  Unique    Oversized  Long Sleeve
2   Sunny        Bright     Floral  Casual        Loose        Tunic
3   Windy       Neutral    Stripes  Trendy        Tight       Peplum
4   Windy       Neutral    Stripes  Trendy        Tight        Shirt

In [6]:
df.shape

(1000, 6)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Weather        1000 non-null   object
 1   Color Palette  1000 non-null   object
 2   Pattern        1000 non-null   object
 3   Feeling        1000 non-null   object
 4   Clothing Fit   1000 non-null   object
 5   Dress Name     1000 non-null   object
dtypes: object(6)
memory usage: 47.0+ KB


In [8]:
df['Weather'] = df['Weather'].astype(str)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   Weather        1000 non-null   object
 1   Color Palette  1000 non-null   object
 2   Pattern        1000 non-null   object
 3   Feeling        1000 non-null   object
 4   Clothing Fit   1000 non-null   object
 5   Dress Name     1000 non-null   object
dtypes: object(6)
memory usage: 47.0+ KB


In [10]:
df['T1'] = df['Weather'].str.cat(df['Color Palette'].astype(str), sep=',')

In [11]:
df.head()

Weather Color Palette    Pattern Feeling Clothing Fit   Dress Name  \
0   Windy       Neutral    Stripes  Trendy        Tight      Bodycon   
1   Snowy         Earth  Geometric  Unique    Oversized  Long Sleeve   
2   Sunny        Bright     Floral  Casual        Loose        Tunic   
3   Windy       Neutral    Stripes  Trendy        Tight       Peplum   
4   Windy       Neutral    Stripes  Trendy        Tight        Shirt   

              T1  
0  Windy,Neutral  
1    Snowy,Earth  
2   Sunny,Bright  
3  Windy,Neutral  
4  Windy,Neutral

In [12]:
df['T2'] = df['Pattern'].str.cat(df['Feeling'].astype(str), sep=',')

In [13]:
df.head()

Weather Color Palette    Pattern Feeling Clothing Fit   Dress Name  \
0   Windy       Neutral    Stripes  Trendy        Tight      Bodycon   
1   Snowy         Earth  Geometric  Unique    Oversized  Long Sleeve   
2   Sunny        Bright     Floral  Casual        Loose        Tunic   
3   Windy       Neutral    Stripes  Trendy        Tight       Peplum   
4   Windy       Neutral    Stripes  Trendy        Tight        Shirt   

              T1                T2  
0  Windy,Neutral    Stripes,Trendy  
1    Snowy,Earth  Geometric,Unique  
2   Sunny,Bright     Floral,Casual  
3  Windy,Neutral    Stripes,Trendy  
4  Windy,Neutral    Stripes,Trendy

In [14]:
df['T3'] = df['T1'].str.cat(df['T2'].astype(str), sep=',')

In [15]:
df.head()

Weather Color Palette    Pattern Feeling Clothing Fit   Dress Name  \
0   Windy       Neutral    Stripes  Trendy        Tight      Bodycon   
1   Snowy         Earth  Geometric  Unique    Oversized  Long Sleeve   
2   Sunny        Bright     Floral  Casual        Loose        Tunic   
3   Windy       Neutral    Stripes  Trendy        Tight       Peplum   
4   Windy       Neutral    Stripes  Trendy        Tight        Shirt   

              T1                T2                            T3  
0  Windy,Neutral    Stripes,Trendy  Windy,Neutral,Stripes,Trendy  
1    Snowy,Earth  Geometric,Unique  Snowy,Earth,Geometric,Unique  
2   Sunny,Bright     Floral,Casual    Sunny,Bright,Floral,Casual  
3  Windy,Neutral    Stripes,Trendy  Windy,Neutral,Stripes,Trendy  
4  Windy,Neutral    Stripes,Trendy  Windy,Neutral,Stripes,Trendy

In [16]:
df['Text'] = df['T3'].str.cat(df['Clothing Fit'].astype(str), sep=',')

In [17]:
df.head()

Weather Color Palette    Pattern Feeling Clothing Fit   Dress Name  \
0   Windy       Neutral    Stripes  Trendy        Tight      Bodycon   
1   Snowy         Earth  Geometric  Unique    Oversized  Long Sleeve   
2   Sunny        Bright     Floral  Casual        Loose        Tunic   
3   Windy       Neutral    Stripes  Trendy        Tight       Peplum   
4   Windy       Neutral    Stripes  Trendy        Tight        Shirt   

              T1                T2                            T3  \
0  Windy,Neutral    Stripes,Trendy  Windy,Neutral,Stripes,Trendy   
1    Snowy,Earth  Geometric,Unique  Snowy,Earth,Geometric,Unique   
2   Sunny,Bright     Floral,Casual    Sunny,Bright,Floral,Casual   
3  Windy,Neutral    Stripes,Trendy  Windy,Neutral,Stripes,Trendy   
4  Windy,Neutral    Stripes,Trendy  Windy,Neutral,Stripes,Trendy   

                                     Text  
0      Windy,Neutral,Stripes,Trendy,Tight  
1  Snowy,Earth,Geometric,Unique,Oversized  
2        Sunny,Bright,Floral,Casual,Loose  
3      Windy,Neutral,Stripes,Trendy,Tight  
4      Windy,Neutral,Stripes,Trendy,Tight

In [18]:
df = df.drop(columns=['Weather', 'Color Palette', 'Pattern', 'Feeling', 'Clothing Fit','T1','T2','T3'])


In [19]:
df.head()

Dress Name                                    Text
0      Bodycon      Windy,Neutral,Stripes,Trendy,Tight
1  Long Sleeve  Snowy,Earth,Geometric,Unique,Oversized
2        Tunic        Sunny,Bright,Floral,Casual,Loose
3       Peplum      Windy,Neutral,Stripes,Trendy,Tight
4        Shirt      Windy,Neutral,Stripes,Trendy,Tight

In [20]:
df.shape

(1000, 2)

In [21]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 1000):
  text = re.sub('[^a-zA-Z]', ' ', df['Text'][i])
  text = text.lower()
  text = text.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  text = [ps.stem(word) for word in text if not word in set(all_stopwords)]
  text = ' '.join(text)
  corpus.append(text)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [22]:
import sklearn
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
     

In [23]:
y = df.iloc[:, 0].values

In [24]:
y

array(['Bodycon', 'Long Sleeve', 'Tunic', 'Peplum', 'Shirt', 'Sweater',
       'Wrap', 'Maxi', 'Bodycon', 'A-Line', 'Peplum', 'Turtleneck',
       'T-Shirt', 'Long Sleeve', 'Knit Sweater', 'Sweater', 'Sheath',
       'Shift', 'Tunic', 'A-Line', 'Turtleneck', 'Fit and Flare',
       'Fit and Flare', 'Shift', 'Sweater', 'Turtleneck', 'Maxi', 'Maxi',
       'Fit and Flare', 'A-Line', 'Wrap', 'Wrap', 'Kaftan', 'Shift',
       'Turtleneck', 'Peplum', 'Shift', 'Shift', 'Peplum', 'Shift',
       'Sheath', 'Turtleneck', 'Peplum', 'Knit Sweater', 'Sheath',
       'Sheath', 'Peplum', 'Maxi', 'Tunic', 'Shirt', 'Fit and Flare',
       'Sweater', 'Wrap', 'Long Sleeve', 'Pencil', 'Wrap', 'Shift',
       'Tunic', 'Shift', 'Knit Sweater', 'Sweater', 'Sheath',
       'Turtleneck', 'Kaftan', 'Sweater', 'Turtleneck', 'Peplum',
       'Peplum', 'Maxi', 'Knit Sweater', 'Shift', 'Knit Sweater',
       'Sweater', 'A-Line', 'Pencil', 'Pencil', 'Boho Midi',
       'Knit Sweater', 'Pencil', 'Sheath', 'Boho Midi

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [26]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [27]:

y_pred = classifier.predict(X_test)

In [28]:

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  7  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  9  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 14  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 10  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  9  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 10  0]
 [ 0  0  0  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 14  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

0.175

In [29]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  7  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  9  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  9  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 14  0  0]
 [ 0  0  0  0  0 15  0  0  0  0  0  0  0  0  0  0  0  0

0.185

In [31]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  7  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  9  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 14  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 10  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  9  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 10  0]
 [ 0  0  0  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 14  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

0.175

In [33]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [34]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  7  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  9  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 14  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 10  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  9  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 10  0]
 [ 0  0  0  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 14  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0

0.175

In [35]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [50]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  7  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  9  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 14  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 10  0  0  0  0]
 [ 0  0  0  0  0  0  0  9  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 10  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 11  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 15  0  0

0.205

In [38]:
# Sample input
x1 = "Sunny,Bright,Floral,Casual,Loose"

# Assuming 'classifier' is your pre-built and pre-trained model
# and 'cv' is your fitted CountVectorizer

def prediction(ex1):
    # Ensure the input is a string
    ex1 = str(ex1)

    # Text preprocessing
    new_text = re.sub('[^a-zA-Z]', ' ', ex1)
    new_text = new_text.lower()
    new_text = new_text.split()

    ps = PorterStemmer()
    all_stopwords = stopwords.words('english')
    all_stopwords.remove('not')

    new_text = [ps.stem(word) for word in new_text if word not in set(all_stopwords)]
    new_text = ' '.join(new_text)

    # Transform the input text
    X_prediction = cv.transform([new_text]).toarray()

    # Predict using the pre-trained classifier
    y_prediction = classifier.predict(X_prediction)
    return y_prediction

# Run the prediction function
print(prediction(x1))

['Maxi']
